### PR TITLE
fix: fixed inclusion of aw-webui for use with aw-server-rust (fixes #441)

### LINKED ISSUE #441: Switching to aw-server-rust instead of aw-server gives 404 in WebUI
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS version and name**: MacOS Mojave 10.14.6
- **ActivityWatch version**: 0.9.2

## Describe the bug

Switching on `aw-server-rust` and turning off `aw-server` seems to result in some of the dashboard (WebUI) functionality missing. I have verified that `aw-server-rust` is running since `http://localhost:5600/api/0/buckets/` actually returns what you would expect when it's on.

## To Reproduce

1. Download the latest ActivityWatch for macOS (https://github.com/ActivityWatch/activitywatch/releases/download/v0.9.2/activitywatch-v0.9.2-macos-x86_64.dmg)
2. Install by copying the `.app` to the `Applications` directory
3. Open ActivityWatch (doing the Security & Privacy preferences dance to open it)
4. Grant ActivityWatch required permissions under Accessibility and also under Automation (System Events).
5. Open the WebUI by going to http://localhost:5600
6. Disable `aw-server` by opening the tray icon > modules and clicking `aw-server`.
7. Enable `aw-server-rust` by opening the tray icon > modules and clicking `aw-server-rust`.
8. Reload the WebUI at http://localhost:5600 and get a 404 json reponse `{"reason":"Resource was not found.","status":404}`

## Expected behavior

The expectation is that reloading the WebUI after switching to `aw-server-rust` in step 8 would give the same result as the `aw-server` running in step 5.

## Documentation

Here's a bit from the `aw-server-rust` logs:
```
[2020-06-15][08:27:36][aw_server][INFO] Using DB at path "/Users/mpeteuil/Library/Application Support/activitywatch/aw-server-rust/sqlite.db"
[2020-06-15][08:27:36][aw_server][WARN] Unable to find an aw-webui asset path which exists, falling back to ./aw-webui/dist
[2020-06-15][08:27:36][aw_server][INFO] Using aw-webui assets at path "./aw-webui/dist/"
[2020-06-15][08:27:36][aw_server::endpoints][INFO] Starting aw-server-rust at 127.0.0.1:5600
[2020-06-15][08:27:36][rocket::rocket][WARN] environment is 'production', but no `secret_key` is configured
[2020-06-15][08:27:37][_][ERROR] No matching routes for OPTIONS /api/0/buckets/aw-watcher-web-firefox/heartbeat?pulsetime=80.
[2020-06-15][08:27:37][_][WARN] Responding with 404 Not Found catcher.
[2020-06-15][08:27:45][_][WARN] Response was `None`.
[2020-06-15][08:27:45][_][WARN] Responding with 404 Not Found catcher.
```

The `No matching routes for OPTIONS` message is most of the log file as you might expect with it being a heartbeat.

## Additional context
If there's more that could be helpful let me know and I'll add it.

### PR DESCRIPTION
**Pull request by ErikBjare**
Fixes #441

I have no idea if I'm doing this right.

Does it look correct to you @xylix? I guess we'll have to test it anyway but would be nice to understand how things really work here. 

I ran `7z x activitywatch-v0.9.2-macos-x86_64.dmg` to inspect the last released `dmg` and get an understanding of how things are structured, but found more questions than answers.

Questions:
 - What is the working directory for aw-server-rust when run on macOS?
 - Will aw-server-rust find the files in `ActivityWatch.app/Contents/Resources/aw-server-rust/static` without changes? (@johan-bjareholt)

### CODE REVIEW

**Comment by xylix** [comment]
I'm pretty sure working directory of aw-server-rust on macOS is defined by how aw-qt starts it. Most probably in a subfolder within the .app directory.

The changes look sensible to me.

I tried to do a test build on my mac and (poetry version 1.0.10) got a poetry error. Don't have time to debug this tonight but I'll gladly try if we get a CI built .dmg or can debug this next week. 
```
poetry install
The lock file might not be compatible with the current version of Poetry.
Upgrade Poetry to ensure the lock file is read properly or, alternatively, regenerate the lock file with the `poetry lock` command.
Installing dependencies from lock file

[NonExistentKey]
'Key "reference" does not exist.'
make[1]: *** [build] Error 1
make: *** [build] Error 2
```

On another note about release 0.10: I recently bought an Apple developer license so we can now officially sign AW macOS app without giving users the unnecessary warnings. Haven't had time to test if that fixes the other issues latest macOS versions have had :/. But at least we have the ability to sign properly now.

**Comment by ErikBjare** [comment]
@xylix I think you just need to update poetry. That's great about the dev license!

I just found a reasonable guide to getting macOS working in a VM, so I'm giving that a shot: https://www.funkyspacemonkey.com/how-to-install-macos-catalina-on-linux

**Comment by ErikBjare** [comment]
I think I've fixed it now by adding some `asset_path` detection code in https://github.com/ActivityWatch/aw-server-rust/pull/186. Waiting for the build to complete in CI so I can test it.

In general, running ActivityWatch on macOS using the `.app` was smoother than expected (at least on Catalina). Haven't faced any particular issues.

**Comment by ErikBjare** [comment]
Works now (built manually instead since I was having some issues), merging.

**Comment by xylix** [comment]
Great work!

**Pull request merged**
