### PR TITLE
Create a MacOS .app for the whole ActivityWatch.

### PR DESCRIPTION
**Pull request by xylix**
By going into the .app directory and trying to run ./aw-qt while not having my virtualenv active, I got the error `FileNotFoundError: [Errno 2] No such file or directory: 'aw-server': 'aw-server'`.

I decide to try to pack the whole activitywatch into an .app to see if this would fix the problem. It did fix the problem, I now have .app files that run succesfully (at least on my system). However building the mega-bundle requires pyinstaller dev version (>=4.0). 

I'd appreciate linux testing that I didn't break anything, and testing the pyinstaller-mega-package on non-macos systems would probably also be a good idea before merging anything.

---

Notes by maintainers:

 - [x] ~~Wait for PyInstaller 4.0 to get released~~ We're not going to wait.
 - [x] Add to CI process (fixed in #336)

The bundle produced could/might be used exclusively for macOS, to prevent breakage on other platforms.

### CODE REVIEW

**Comment by ErikBjare** [comment]
Wow, awesome work! 

Happy you tried out the dev version of PyInstaller that we've been waiting for, now all that remains is for PyInstaller 4.0 to get released and then I'll do some final testing.

Again, amazing work ❤️

**Comment by xylix** [comment]
Happy to help :). Activitywatch is an amazing piece of software!

**Comment by matjazmav** [comment]
Can you sign app bundle?

**Comment by ErikBjare** [comment]
Hopefully, I'll look into it.

I just got an old MacBook from a colleague, so I'll be able to work on this
as soon as I find the time.

**Comment by ErikBjare** [comment]
I've managed to get this working on the old mid-2010 MBP I got to borrow, amazing work! Works when double-clicked and everything.

A few things:

 - The logo doesn't seem to be set correctly
 - The version isn't set in the Info.plist

I'll try adding the step to CI.

**Comment by xylix** [comment]
The version can be set inside the `aw.spec` file at
```
app = BUNDLE(awq_coll,
                 aww_coll,
                 awa_coll,
                 aws_coll,
                 name="ActivityWatch.app",
                 icon=icon,
                 bundle_identifier="ActivityWatch",
                 info_plist={"CFBundleExecutable": "MacOS/aw-qt",
                             "CFBundleIconFile": "logo.ico"})
```
inside the info_plist dictionary. 

I didn't notice the logo problem, but right now I have no idea what the problem is since we do set the logo for the `info.plist` in the aw.spec (see `"CFBundleIconFile": "logo.ico"` in the upper snippet). Maybe the logo isn't found for some reason? 

Using create-dmg or something equivalent sounds like a good idea. There was some dicussion in pyinstaller repo about .dmg support and seems like it's not happening soon (https://github.com/pyinstaller/pyinstaller/issues/2208 )

**Comment by xylix** [comment]
Okay I did some research, I think the icon failure is related to not having a MacOS specific icon format (".icns"). (https://stackoverflow.com/questions/646671/how-do-i-set-the-icon-for-my-applications-mac-os-x-app-bundle )

Also found some instructions on converting a .png icon to an iconset and then forward into an icns file (https://stackoverflow.com/questions/12306223/how-to-manually-create-icns-files-using-iconutil ).

**Comment by xylix** [comment]
I think the version number here https://github.com/ActivityWatch/aw-core/blob/master/aw_core/__about__.py is old? (0.4.1). I am trying to use aw_core for the version info since aw.spec doesn't import aw_server which is used elsewhere for version info.

I got the version info to work, but the icon not. (Probably related to https://github.com/pyinstaller/pyinstaller/issues/4574 )

**Comment by xylix** [comment]
BTW I don't think registering as an apple developer is necessary. It should be possible to sign the .app with a self created cert or just use create-dmg unsigned.

**Comment by ErikBjare** [comment]
Sorry for not mentioning it, but I fixed the icon and version here: https://github.com/ActivityWatch/activitywatch/pull/336

**Comment by xylix** [comment]
No problem that's great :).

**Comment by xylix** [comment]
I pushed my changes implementing the .dmg building since I already worked on them, you may use them if necessary :).

**Comment by ErikBjare** [comment]
I took your changes and added fixes for the final things (mainly CI integration) in #336 and will be merging it as soon as CI passes.

Thanks again for such a great PR, this'll make ActivityWatch a lot easier to install for macOS users :)

**Comment by xylix** [comment]
Great work! Hope I can contribute something in the future as well :)

**Comment by rathishkumar** [comment]
@ErikBjare I tried `make package` on Windows and I am able to generate installable exe file. Now I am testing with packaging for Mac OS.

In package-all.sh I have hardcoded platform as as `macos` and I ran `make package`, no errors, I am seeing a zip file with macos name on /dist.

How do I install it in Mac OS VM running on Windows machine? I am not seeing .app file - again I am seeing only Windows related files only.

**Comment by xylix** [comment]
@rathishkumar You need to run `make ActivityWatch.app`  and that needs to be done on a mac to build the .app.

**Comment by rathishkumar** [comment]
@xylix Thanks, do I need to copy the directory to MacOS and create virtual environment and run the mentioned command on VM to package? Or will it work in Windows itself?

**Comment by xylix** [comment]
You shouldn't copy it since then there are windows installed dependencies. You should clone the repo / your fork and run `make` and `make ActivityWatch.app` in the VM, installing dependencies as required

**Comment by rathishkumar** [comment]
@xylix Thank you, its really awesome, very quick reply.

**Comment by rathishkumar** [comment]
@xylix I did the as you mentioned, make package was successful with zip file containing .`so` file and modules in that were running.

But I could not find `.app` file and there unable to run `make AppWatch.app` (there is no syntax for this in Makefile) I am new to this and missing something, please help on this.

**Comment by ErikBjare** [comment]
@rathishkumar if you look in the Makefile you can see that it's `make dist/ActivityWatch.app` (and dist/ActivityWatch.dmg, which is probably what you want to distribute).

Also, could we have more details on what you are building? 

And remember that ActivityWatch is MPL-2.0, so you must share your changes if you distribute modified versions of it :)

**Comment by rathishkumar** [comment]
@ErikBjare I am building  Usage pattern analytics, but still now I struggling to package as Windows and Mac OS executable with same downloaded package without changes.

I am new to this and thought of doing some app during quarantine. Please let me know, if I do some changes in future, Can't I use it? Consider I am building analytics app as I said and use Activity Watch for data collection - not dashboard part?

I am open to learning, no offence, if it cannot be used, I will look for something else, its been good experience learning new program things.

**Comment by ErikBjare** [comment]
That's fine, and you can absolutely still use it, but if you make changes to existing files you must share them. Read the terms of the MPL-2.0 for details.

**Comment by rathishkumar** [comment]
Thank you @ErikBjare. I am planning to use part of it / (or may be only logic and I will write my own), what I have to change in this case, only changed part or share my project (still learning github for uploading files). Will it be reviewed or modified? just curiosity. 

**If it is taking up your time, you can ignore this question.

**Comment by ErikBjare** [comment]
Read the MPL-2.0 FAQ I linked, it should answer your question.

**Pull request closed without merging**
