### PR TITLE
Moved build/install/test scripts to Makefile

### PR DESCRIPTION
**Pull request by ErikBjare**
# Before merging
- [x] merge all dev/makefile branches in submodules

### CODE REVIEW

**Comment by johan-bjareholt** [comment]
A "make test" that tests all submodules would also be useful

**Comment by johan-bjareholt** [comment]
Seems like i am unable to test a lot of this on arch due to it having python 3.6 and pyinstaller doesn't have support for 3.6 yet.

Another thing i found was this in the .spec files in aw-watcher-window and aw-watcher-afk

     pathex=['/home/erb/Programming/activitywatch/aw-watcher-afk'],

**Comment by ErikBjare** [comment]
@johan-bjareholt Yeah I know, PyInstaller is a pain.

The pathex thing is probably not needed, Travis and AppVeyor doesn't seem to care anyway.

**Comment by ErikBjare** [comment]
I'll go ahead and merge this into the v0.7 branch now.

**Pull request merged**
