### PR TITLE
Add some dependency caching, fix a couple of travis warnings

### PR DESCRIPTION
**Pull request by xylix**
These are the least refactory and most working changes from the travis things I tried today.

Renaming the "matrix", local_dir and removing skip_cleanup is just moving to more recent travis standards, and they don't change the build at all.

These caches should make the build somewhat faster with no real downside. Pip, .rustup and brew caches are fairly safe, and cargo's target should also be faster than recompiling dependencies etc. every time, but it will still rebuild the relevant artifacts if source files have changes.

### CODE REVIEW

**Comment by ErikBjare** [comment]
Nice, I'll review tomorrow when the builds have passed :)

**Comment by johan-bjareholt** [comment]
aw-server-rust seems to be failing on the integration tests for Linux, try just updating the aw-server-rust submodule to the latest version and re-run.

**Comment by ErikBjare** [comment]
@johan-bjareholt The test_full Hyper(IncompleteMessage) error seems to be a recurring culprit in CI, failing every now and again (has delayed many PRs now). 

Can you fix it?

**Comment by johan-bjareholt** [comment]
@ErikBjare This might fix it, just pushed

https://github.com/ActivityWatch/aw-server-rust/commit/8901c9c0c0ba27a181ef03247ea3949b95a738bb

**Comment by xylix** [comment]
SInce the fix passed in travis I pulled it here as well.

**Comment by johan-bjareholt** [comment]
Okay, still not passing.

I also just noticed that it does in fact not pass in the aw-server-rust repo either, travis is green but the test actually fails

**Comment by johan-bjareholt** [comment]
I have a second guess.

The linux build might be racing if it's fast at starting the webserver so calling get_info is fine but it's slow at starting the datastore so the first call to get_buckets is not ready yet and is returning something that aw-client-rust is not expecting.

As I said though, this is just a guess.

**Comment by ErikBjare** [comment]
>I also just noticed that it does in fact not pass in the aw-server-rust repo either, travis is green but the test actually fails

This is concerning...

**Comment by ErikBjare** [comment]
I created an issue for the blinking test in https://github.com/ActivityWatch/aw-server-rust/issues/92

**Pull request merged**
