### PR TITLE
Fix Windows PyInstaller builds

### PR DESCRIPTION
**Pull request by johan-bjareholt**
Downgrade and lock PyInstaller version to 3.3.1 to fix windows builds

### CODE REVIEW

**Comment by ErikBjare** [comment]
@johan-bjareholt Just FYI, I've fixed some tests and stuff in #274 that you might want to merge in, or review and then merge into master.

**Comment by johan-bjareholt** [comment]
@ErikBjare There's quite a bit here that will be scapped, but I seem to be on the right track to fixing the Windows build. I'll review yours and we should take yours in first.

**Comment by johan-bjareholt** [comment]
Windows artifact from appveyor now works!

Solution was to set pyinstaller version to 3.3.1 and jsonschema version for aw-server to 2.6.0 and remove some "--upgrade" flags from pip in the Makefiles.

**Comment by johan-bjareholt** [comment]
@ErikBjare Rebased and now works on Windows again.
Did some direct pushes to master on aw-server, aw-watcher-afk, aw-watcher-window and aw-qt where I remove --upgrade so they don't update the locked-down version of jsonschema on aw-core.

Merge?

**Comment by ErikBjare** [comment]
Go go go!

**Comment by johan-bjareholt** [comment]
Final windows build finished and tested again and still works, merging!

**Pull request merged**
